name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: "12"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Crypto.dll"
changelog: |2-
  ### Bug Fixes ###
  - Clear config when loading page (#115) @crobibero

  ### Code or Repo Maintenance ###
  - chore(deps): bump MailKit from 3.1.1 to 3.2.0 (#108) @dependabot
  - chore(deps): bump Handlebars.Net from 2.1.0 to 2.1.2 (#111) @dependabot

  ### Dependency updates ###
  - chore(deps): bump MailKit from 3.1.1 to 3.2.0 (#108) @dependabot
  - chore(deps): bump Handlebars.Net from 2.1.0 to 2.1.2 (#111) @dependabot
